// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ao7KhScHTUR4gfQQ8tfROqnyzlUVjb0',
    appId: '1:65742393824:web:9a391ba8e731d6e3f41b85',
    messagingSenderId: '65742393824',
    projectId: 'ichat-b80ae',
    authDomain: 'ichat-b80ae.firebaseapp.com',
    storageBucket: 'ichat-b80ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs9-XhR_LakZ-WT4O8mkfONcgQhq7Iz1k',
    appId: '1:65742393824:android:dd2aeb4d410f2c58f41b85',
    messagingSenderId: '65742393824',
    projectId: 'ichat-b80ae',
    storageBucket: 'ichat-b80ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMqHGopNtxYd9IOz0qzeB7K3_Mx7wKAwY',
    appId: '1:65742393824:ios:ca810be333d38594f41b85',
    messagingSenderId: '65742393824',
    projectId: 'ichat-b80ae',
    storageBucket: 'ichat-b80ae.appspot.com',
    androidClientId: '65742393824-3niaoq0ot89p43ugpogeca2ponj4gsfu.apps.googleusercontent.com',
    iosClientId: '65742393824-l912reiqb4rp23bsrpfmjehqkfokb7ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMqHGopNtxYd9IOz0qzeB7K3_Mx7wKAwY',
    appId: '1:65742393824:ios:ca810be333d38594f41b85',
    messagingSenderId: '65742393824',
    projectId: 'ichat-b80ae',
    storageBucket: 'ichat-b80ae.appspot.com',
    androidClientId: '65742393824-3niaoq0ot89p43ugpogeca2ponj4gsfu.apps.googleusercontent.com',
    iosClientId: '65742393824-l912reiqb4rp23bsrpfmjehqkfokb7ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4ao7KhScHTUR4gfQQ8tfROqnyzlUVjb0',
    appId: '1:65742393824:web:89a2af86e9c53f6bf41b85',
    messagingSenderId: '65742393824',
    projectId: 'ichat-b80ae',
    authDomain: 'ichat-b80ae.firebaseapp.com',
    storageBucket: 'ichat-b80ae.appspot.com',
  );

}